### ISSUE TITLE
fail in repo synchronization

### ISSUE THREAD

**Issue by louloux88** [TechNexion/tn-imx-yocto-manifest#13]
Hi, 
am not a expert in building images with Yocto but am trying to build one for my pico-imx8mm on sd card. Sadly when I follow the README doc, it fails at the command _"repo sync -j8"_ with the error: _"fatal: couldn't find remote ref refs/heads/zeus_5.4.24-2.1.0-next"_
Do you have any ideas of the issue for this problem i have?
Thanks a lot for your help :)

**Comment by richard-hu** [comment]
@louloux88 

We are migrating `zeus_5.4.24-2.1.0` to `zeus_5.4.70-2.3.0`.
For PICO-IMX8MM, we improve a lot on `zeus_5.4.70-2.3.0`. 
The stable zeus release will be based on this kernel version and published in the end of April.


I miss to update the instructions on github.

Could you try the updated command as follows?
`repo init -u https://github.com/TechNexion/tn-imx-yocto-manifest.git -b zeus_5.4.y-next -m imx-5.4.70-2.3.0.xml`

I'm sorry for the inconvenience.

BR,

Richard

**Comment by Livius90** [comment]
Will pico-imx7 be supported in the next zeus_5.4 release?

**Comment by richard-hu** [comment]
@Livius90 

Yes. PICO-IMX7 is in the zeus_5.4 release list.

BR,

Richard

**Comment by Livius90** [comment]
Thx the info.
I was just in a little panic because there is no any imx7 in Machine list only the imx6 and imx8 available now in [Readme](https://github.com/TechNexion/tn-imx-yocto-manifest/blob/zeus_5.4.y-next/README.adoc).

**Comment by louloux88** [comment]
Thank you very much for your help! It worked perfectly. Now is the bitbake command which sends me warnings and errors after 20% completation. I'll work on it!


> Could you try the updated command as follows?
> `repo init -u https://github.com/TechNexion/tn-imx-yocto-manifest.git -b zeus_5.4.y-next -m imx-5.4.70-2.3.0.xml`
