### ISSUE TITLE
When will you have a manifest for dunfell?

### ISSUE THREAD

**Issue by tbandtg** [TechNexion/tn-imx-yocto-manifest#16]
When will dunfell be available?

**Comment by johnweber** [comment]
Our plan is to add Gatesgarth support in order to follow NXP's releases.

**Comment by indyIOT** [comment]
Do you have a projected release of Gatesgarth?

**Comment by johnweber** [comment]
We targeting a release of some platforms later this month, leading with EDM-G-IMX8M-PLUS.
