### ISSUE TITLE
I need libgpiod 1.6 in my imx7d-pico with Yocto/Zeus

### ISSUE THREAD

**Issue by patusaembedded** [TechNexion/tn-imx-yocto-manifest#17]
Hi,

I stay trying **this tutorial:** https://github.com/TechNexion/tn-imx-yocto-manifest/tree/zeus_5.4.y-next  (Video about this: https://www.youtube.com/watch?v=Gc4_g6uxUQo&list=PLDKAMFzaz6bhxPKZtAMOx0cr3LazUmEr3&index=1&t=304s)  **and this**: https://hub.mender.io/t/technexion-pico-pi-imx7/136/40  **since the middle of last year**

The second link-tutorial I can generate the image but I can't have libgpiod version **1.6 (only 1.4**, which doesn't suit me)

The first link I can't generate the image. The error I get is: https://gist.github.com/patusaembedded/471195569ce8cf4a109ce16164da4050  (
**sources/poky/meta/classes/buildstats.bbclass:103: SyntaxWarning: "is" with a literal. Did you mean "=="?  if status is "passed":)**   **After this commands**:

1) MACHINE=pico-imx7 DISTRO=fsl-imx-xwayland source tn-setup-release.sh -b build-xwayland
2)  bitbake fsl-image-qt5-validation-imx

My questions is:

1) **How to solve the issue occurred on link 1 ?**

2) **How can I put ligpiod version 1.6 in my imx7d-pico (yocto/zeus) ?**

![build result missing key images](https://user-images.githubusercontent.com/71419485/121819173-166c7500-cc62-11eb-8dcb-ab5e1b65b3e7.png)

**Comment by patusaembedded** [comment]
Now I can pico-imx7 (without "d")  Zeus/Yocto/image in my imx7d-pico (without SSH) because I choose core-image-minimal (I think)

But the main problem now is that I need libgpiod **v1.6** and not 1.4 (picture below). As per question 2 above. **How to achieve this?**

https://github.com/openembedded/meta-openembedded/issues/372

![Captura de tela de 2021-06-13 22-29-27](https://user-images.githubusercontent.com/71419485/121828727-d4a9f180-cc96-11eb-9325-2730b3181806.png)

**Comment by johnweber** [comment]
meta-oe doesn't migrate to libgpiod v1.6 until version 3.3 (hardknott) and this would naturally come that layer. We are migrating to 3.2 (Gatesgarth).

If you need TechNexion to perform this work, you can contact sales@technexion.com and tell us a bit about your project.

Alternatively, if you really need 1.6 of libgpiod, you can try to backport the libgpiod v1.6 from hardknott yourself. Suggest that you do this in your own higher priority metadata layer.

http://cgit.openembedded.org/meta-openembedded/tree/meta-oe/recipes-support/libgpiod?h=hardknott

**Comment by patusaembedded** [comment]
@johnweber you said : _"backport the libgpiod v1.6 from hardknott yourself"_

As you can see in the issue below (already mentioned above) it is not so easy to do this.

https://github.com/openembedded/meta-openembedded/issues/372

**How can I make this backport correctly?**

**Comment by johnweber** [comment]
This is outside the scope of support for TechNexion hardware as this pertains to software usage only, and is not hardware-dependent.  For further support please reach out to sales@technexion.com and please also be prepared to discuss your project.

**Comment by patusaembedded** [comment]
@johnweber **How can I make this backport correctly?**

**Comment by johnweber** [comment]
Please reach out to sales@technexion.com and provide the following information:
- Project description
- Schedule
- 1st, 2nd, and 3rd year purchase quantity

Then our sales team can make a recommendation regarding how to support you.

**Comment by patusaembedded** [comment]
**How can I make this backport correctly****?**

**Comment by johnweber** [comment]
@patusaembedded You can also try using mainline Yocto, which has support for PICO-IMX7D, or doing the work to port this yourself.
Regardless, this issue is not pertaining to a bug or issue with the BSP or hardware, therefore it is invalid.

**Comment by patusaembedded** [comment]
Invalid are you(s) to provide SW support, much less HW
