### ISSUE TITLE
imx7d+brcm - wifi/bt not working

### ISSUE THREAD

**Issue by pam-31** [TechNexion/tn-imx-yocto-manifest#18]
imx7d+brcm - wifi and bt are not working in Zeus 5.4.y
Despite setting WIFI_MODULE=brcm, the compiled device tree has QCA extension!
During boot, wifi test is failed and HW is not booted; I have bypassed the test
and brought the HW up, but have no wifi/bt; all the needed files are there:

[root@pico-imx7:/# ls /lib/firmware/brcm -al
total 1892
drwxr-xr-x 2 root root   4096 Jun 15 16:42 .
drwxr-xr-x 5 root root   4096 Jun 15 16:42 ..
-rwxr-xr-x 1 root root  66840 Jun 10 20:57 bcm4339a0.hcd
-rwxr-xr-x 1 root root  40568 Jun 10 20:57 bcm43438a0.hcd
-rwxr-xr-x 1 root root 541314 Jun 10 20:57 fw_bcm4339a0_ag.bin
-rwxr-xr-x 1 root root 541314 Jun 10 20:57 fw_bcm4339a0_ag_apsta.bin
-rwxr-xr-x 1 root root 405428 Jun 10 20:57 fw_bcm43438a0.bin
-rwxr-xr-x 1 root root 405428 Jun 10 20:57 fw_bcm43438a0_apsta.bin
-rwxr-xr-x 1 root root    979 Jun 10 20:57 nvram_ap6212.txt
-rwxr-xr-x 1 root root   2366 Jun 10 20:57 nvram_ap6335.txt](url)

**Comment by johnweber** [comment]
We discontinued support for modules with BRCM radios in 2019, and aren't planning to continue to add support for these radios going forward unless there is very compelling business value.

We hear from software developers in the community that brcmfmac support is working in linux mainline. You may want to try it out.

**Comment by maruel** [comment]
Hi! I understand the business case to reduce complexity. I still believe there's an action item here.

Can you update https://developer.technexion.com/docs/building-an-image-with-yocto? The instructions as of now (in 2025) are misleading into making developers think that `WIFI_MODULE` has an effect on the build.

There should be a documented way to not preload the Qualcomm (QCA) driver to save space.

As an inexperienced developer, I believe it's a matter of setting the right flag in `conf/local.conf` but it's unclear to me how to achieve this yet. It's a bummer especially that, as you mention, "brcmfmac support is working in linux mainline".

Thanks!

**Comment by ray-chang** [comment]
Hi!
We apologize for any inconvenience caused. I have updated the Development Guide.
