### ISSUE TITLE
missing imx8mm-xore-wizard.dtb

### ISSUE THREAD

**Issue by arrow53** [TechNexion/tn-imx-yocto-manifest#2]
I can't build for the xore-imx8mm MACHINE as there is no corresponding dtb in the kernel source. 

https://github.com/TechNexion/linux-tn-imx/tree/tn-imx_4.14.98_2.0.0_ga-stable/arch/arm64/boot/dts/freescale

Any thoughts on where I can get it?

**Comment by richard-hu** [comment]
@arrow53 

Thanks for your feedback.

`xore-imx8mm` is new platform and still in `tn-imx_4.14.98_2.0.0_ga-next` branch.

https://github.com/TechNexion/linux-tn-imx/tree/tn-imx_4.14.98_2.0.0_ga-next/arch/arm64/boot/dts/freescale

According to schedule, `xore-imx8mm` will be merged to `tn-imx_4.14.98_2.0.0_ga-stable` branch in 2020Q2 or 2020Q3.

BR,

Richard

**Comment by arrow53** [comment]
perfect. thanks @richard-hu
