### ISSUE TITLE
TEK3-IMX6 is not supported

### ISSUE THREAD

**Issue by letis33** [TechNexion/tn-imx-yocto-manifest#20]
Hello,

How can I build a Zeus version for TEK3-IMX6 as it is not liisted in the Supported Plarform ?

**Comment by yoooh8668** [comment]
Hi there,

TEK3-IMX6 with yocto 3.0 will release in this weekend, 
But if you do want to try it now, here is the command:
`$ repo init -u https://github.com/TechNexion/tn-imx-yocto-manifest.git -b zeus_5.4.y-next -m imx-5.4.70-2.3.0.xml`
`$ repo sync`
`$ WIFI_FIRMWARE=y WIFI_MODULE=ath-pci DISTRO=fsl-imx-x11 MACHINE=tek-imx6 source tn-setup-release.sh -b build-x11-tek-imx6`
`$ bitbake fsl-image-qt5-validation-imx`

Please do check if the **source/meta-tn-imx-bsp** is in **zeus_5.4.70-2.3.0-next** branch.

THANKS~~
Joe

**Comment by letis33** [comment]
Hi Joe,

Thanks for your reply.
