### ISSUE TITLE
Github security makes bitbake break.

### ISSUE THREAD

**Issue by tbandtg** [TechNexion/tn-imx-yocto-manifest#24]
I can no longer bitbake it says that they have disabled unsecured github pulls.

**Comment by richard-hu** [comment]
This issue results from github changes security policy and they removes  support of “git protocol” in “url”.
https://github.blog/2021-09-01-improving-git-protocol-security-github/
(Although github claimed it last year, they just start to put it in practice several days ago.)

“Poky” upstream has a patch which converts the protocol from “git” to “https” when host is “github” to avoid this problem.
https://git.yoctoproject.org/poky/commit/?h=zeus&id=daf096e295121ea49ebf21f8070e9a6e28f5d46c
We already include this patch in Zeus branch and test the build on our build server.
https://github.com/TechNexion/tn-imx-yocto-manifest/commit/d89437f7719825142cf04513f68f01719ee51660
The build is completed without errors.

Could you try to fetch latest Yocto source again for avoiding this problem?
We will fix this issue in Hardknott branch later. Build server is running to validate the build...

BR,

Richard

**Comment by indyIOT** [comment]
okay, Need hardknott stable too.
