### ISSUE TITLE
Ubuntu with Gnome desktop image building issue

### ISSUE THREAD

**Issue by LeoChang88** [TechNexion/tn-imx-yocto-manifest#25]
hello,

Some error occurred when I building Ubuntu Gnome desktop image with EDM-G-IMX8M-PLUS.
please refer to the log file.
[error.txt](https://github.com/TechNexion/tn-imx-yocto-manifest/files/7867096/error.txt)
I have tried several different internet sources, but not working.

**Comment by wigcheng** [comment]
Okay I saw it :)
Thanks for your reminder.

I still processing Ubuntu Gnome compiling issue because two items update:
1. NXP update some new patches for Gnome desktop optimization.
2. Github security issue

Could be fix it tomorrow, I'll let you know here when I've done.
Thanks for your understand.

**Comment by LeoChang88** [comment]
@wigcheng Any updates?

**Comment by wigcheng** [comment]
Sorry, no update you imminently, it works I think, did you still got failed message?

**Comment by LeoChang88** [comment]
@wigcheng Still got error,  full log:
[build_log_.txt](https://github.com/TechNexion/tn-imx-yocto-manifest/files/8166172/build_log_.txt)

**Comment by richard-hu** [comment]
@LeoChang88 :

We figure out the commits in `tn-imx-5.10.72-hardknott-stable` branch of "meta-nxp-desktop" is outdated.
We just update the branch to make it the same as `tn-imx-5.10.72-hardknott` branch.
Could you execute the repo command to update Yocto repos?

Please ensure the SHA id for `meta-nxp-desktop` is `6a53f8bc7ba6bc5c441bc76925aa5d1dc1a3a798`.
```
Build Configuration:
BB_VERSION           = "1.50.0"
BUILD_SYS            = "x86_64-linux"
NATIVELSBSTRING      = "ubuntu-20.04"
TARGET_SYS           = "aarch64-fsl-linux"
MACHINE              = "edm-g-imx8mp"
DISTRO               = "imx-desktop-xwayland"
DISTRO_VERSION       = "1.0"
TUNE_FEATURES        = "aarch64 armv8a crc cortexa53 crypto"
TARGET_FPU           = ""
meta
meta-poky            = "HEAD:269265c00091fa65f93de6cad32bf24f1e7f72a3"
meta-oe
meta-multimedia
meta-python          = "HEAD:f44e1a2b575826e88b8cb2725e54a7c5d29cf94a"
meta-freescale       = "HEAD:469d6c958c76ea235b3d3c1527e797ce3a7392e3"
meta-freescale-3rdparty = "HEAD:f8150f3b37cb83cba1f9e2378e57bb63e02d4610"
meta-freescale-distro = "HEAD:e6daa26ba1f748326546063d63a085ae671827d9"
meta-bsp
meta-sdk
meta-ml
meta-v2x             = "HEAD:30eff0d5a090d34690f0261b2899d5a5cd94c5ab"
meta-nxp-demo-experience = "HEAD:9dcc11ea9f525cffedbb28895e0abb443e56c3e0"
meta-chromium        = "HEAD:8be1d3a0ba0cf32e61144900597207af5698c10d"
meta-clang           = "HEAD:b0d805060791006d651efd3d7ae3dd5add8f70fe"
meta-gnome
meta-networking
meta-filesystems     = "HEAD:f44e1a2b575826e88b8cb2725e54a7c5d29cf94a"
meta-qt5             = "HEAD:43f8f539d40070a70fe89136db89bf5bb1dfe7ed"
meta-python2         = "HEAD:8db9e4f6ceae33d7a4f55453d31e69f9858af4eb"
meta-virtualization  = "HEAD:7f719ef40896b6c78893add8485fda995b00d51d"
meta-tn-imx-bsp      = "HEAD:b2120c30391111a943c392df8ddbae87db32b2f6"
meta-nxp-nfc         = "HEAD:5d05c57fc8faf3f1bc95c1702e1a6aa78d83412f"
meta-nxp-desktop     = "HEAD:6a53f8bc7ba6bc5c441bc76925aa5d1dc1a3a798"
```

From the log you provide, the SHA id of `meta-nxp-desktop` is `25e2dc5f3e8aaa6a4efbf9ce0743756fcc31d100`.
It's outdated.



BR,

Richard

**Comment by LeoChang88** [comment]
Hi @richard-hu ,

I restarted all step and still got error:
[log0304.txt](https://github.com/TechNexion/tn-imx-yocto-manifest/files/8182461/log0304.txt)
I'm using Chunghwa Telecom so I think it's not a network issue.

**Comment by LeoChang88** [comment]
Update:
According this thread:
https://yoctobbq.lineo.co.jp/?q=node/353
I tried to clone tinycompress individually, and it failed:

ubuntu@ubuntu:~$ git clone git://git.alsa-project.org/tinycompress.git;protocol=git
Cloning into 'tinycompress'...
fatal: unable to connect to git.alsa-project.org:
git.alsa-project.org[0: 207.180.221.201]: errno=Connection refused

Do you have any idea about this?

**Comment by richard-hu** [comment]
Actually, We have no idea...

![圖片](https://user-images.githubusercontent.com/6065214/156707491-54bf6998-c04f-4b3a-83d8-f0e9cced16e2.png)

**Comment by richard-hu** [comment]
It looks like the problem is the server of `alsa-project`.
Maybe you can try to create a bbappend file or tweak tinycompress_1.1.6.bb to replace SRC_URI or feedback this problem  to `alsa-project`. 

https://community.nxp.com/t5/i-MX-Processors/Failed-to-build-yocto-bsp-for-i-MX8-qxpmek/m-p/875280
https://www.alsa-project.org/pipermail/alsa-devel/2008-July/008893.html

BR,

Richard

**Comment by richard-hu** [comment]
@LeoChang88 

Are there still any problem?

The build is completed on our side.  
We are going to close this issue.

BR,

Richard

**Comment by LeoChang88** [comment]
@richard-hu 

Still got error, we will check today.

**Comment by LeoChang88** [comment]
@richard-hu  

[tinycompress_1.1.6.bb.txt](https://github.com/TechNexion/tn-imx-yocto-manifest/files/8203345/tinycompress_1.1.6.bb.txt)
I have tried to replace the SRC_URI in tinycompress_1.1.6.bb, it cloned successfully but still got patch error:
[tiny_log.txt](https://github.com/TechNexion/tn-imx-yocto-manifest/files/8203333/tiny_log.txt)
how can I fix this?

thanks.

**Comment by LeoChang88** [comment]
Update:
I change to another Telecom and it works.
Please close this issue, thanks for the reply.

**Comment by richard-hu** [comment]
@LeoChang88 

Thanks for the feedback.

> [tinycompress_1.1.6.bb.txt](https://github.com/TechNexion/tn-imx-yocto-manifest/files/8203345/tinycompress_1.1.6.bb.txt)
I have tried to replace the SRC_URI in tinycompress_1.1.6.bb, it cloned successfully but still got patch error:
[tiny_log.txt](https://github.com/TechNexion/tn-imx-yocto-manifest/files/8203333/tiny_log.txt)


In `tinycompress_1.1.6.bb` that you modify, change the prefix from `https` to `git`. You already specify to use `https` protocol in `SRC_URI`. So it doesn't need to change to use `https` prefix.


tinycompress_1.1.6.bb
`
SRC_URI = "git://git.alsa-project.org/http/tinycompress.git;protocol=https;branch=master \
`


I just test and it works.
Then, you don't need to switch to another ISP(Internet Service Provider).

BR,

Richard
