### ISSUE TITLE
imx8mp do_rootfs error

### ISSUE THREAD

**Issue by LeoChang88** [TechNexion/tn-imx-yocto-manifest#27]
Hello,

Please help to analyze this error, thanks.
[log0308.txt](https://github.com/TechNexion/tn-imx-yocto-manifest/files/8204277/log0308.txt)

**Comment by wigcheng** [comment]
Did you modify the source code?
It seems bluez conflict but this issue was be fixed last year.

**Comment by LeoChang88** [comment]
@wigcheng No.

**Comment by richard-hu** [comment]
@LeoChang88 

Yesterday we tested the build on two different PCs(One is ubuntu 18.04, and the other is ubuntu 18.04.) , but can't replicate the issue you feedback.

1. Yocto build completes on ubuntu 18.04
![圖片](https://user-images.githubusercontent.com/6065214/157574141-ff0c415b-ac68-45c0-a9cf-a4d9b1be91c7.png)

Release image is generated.
![圖片](https://user-images.githubusercontent.com/6065214/157574325-29353419-f7f4-47fc-b3ee-c5c91af9177c.png)

Instructions for fetching and build:
![圖片](https://user-images.githubusercontent.com/6065214/157574733-5c2b781c-b073-4581-89eb-baeefbc1fb6c.png)


2. Yocto build completes on ubuntu 20.04

![圖片](https://user-images.githubusercontent.com/6065214/157579139-a9abcae8-9a64-4935-915f-03df2b433251.png)

Release image is generated.
![圖片](https://user-images.githubusercontent.com/6065214/157579249-c7bd2506-de66-4f8e-a14a-61807146b8c6.png)

Instructions for fetching and build:
![圖片](https://user-images.githubusercontent.com/6065214/157579375-f7332260-2baa-4d29-bc64-3a0839204e82.png)

**Comment by richard-hu** [comment]
@LeoChang88 :

We are not able to replicate this issue on our side.

Could you try to remove `hciattach-qca` package ?

meta-tn-imx-bsp/conf/machine/tn-base.inc
`IMAGE_INSTALL_append_ubuntu = " hciattach-qca tn-growpart-helper glmark2 tn-ubuntu-custom"`


Or remove the `build` folder and create a new build.

Another option is to use the dockerfile we provide (as the attachment).
[dockerfile.zip](https://github.com/TechNexion/tn-imx-yocto-manifest/files/8220556/dockerfile.zip)

BR,

Richard

**Comment by LeoChang88** [comment]
Hello @richard-hu  
We are trying to rebuild all with larger RAM size (10G->15G) due to virtual machine stuck last time.

**Comment by richard-hu** [comment]
@LeoChang88 

When yocto builds chromium package (in linking stage), it requires a lot physical memory or virtual memory(about 15GB).
If the physical memory is not enough,  increasing SWAP also works. 
BTW, to speed up the build, the tip is to remove chromium package.

But, what is the relationship between this information and the issue you feedback? 

BR,

Richard

**Comment by LeoChang88** [comment]
@richard-hu 

Because we have no idea how this issue happened, so we just try to avoid the interruption of the process.
May I ask how many GB of RAM are you using ?

**Comment by richard-hu** [comment]
@LeoChang88 

The build machine i use is with 32GB DRAM.
![圖片](https://user-images.githubusercontent.com/6065214/157604114-c8cf0fd5-e6b0-40d1-b8e6-d460a4836d01.png)

I don't think this issue is duo to insufficient DRAM.

Do you try to remove hciattach-qca package ?

meta-tn-imx-bsp/conf/machine/tn-base.inc
IMAGE_INSTALL_append_ubuntu = " hciattach-qca tn-growpart-helper glmark2 tn-ubuntu-custom"

**Comment by LeoChang88** [comment]
@richard-hu 
Maybe I can try to remove chromium package first, and remove hciattach-qca if the error still appear.
How can I remove chromium package?

**Comment by richard-hu** [comment]
@LeoChang88 

Remove `chromium-ozone-wayland` in `meta-nxp-desktop/recipes-fsl/images/imx-image-desktop.bb`.
```
IMAGE_INSTALL += "\
	perf \
	firmwared \
	systemd-gpuconfig \
	alsa-state \
	libcogl \
	clutter-gst-3.0 \
	cheese \
	xserver-xorg-xwayland \
	chromium-ozone-wayland \
	tensorflow-lite \
	${ML_NNSTREAMER_PKGS} \
	armnn \
"
```
BR,

Richard

**Comment by LeoChang88** [comment]
@richard-hu 

I have finished the building process, thank you.
By the way, where is the introduction for image flashing?

**Comment by richard-hu** [comment]
@LeoChang88 

The target image is in the following folder:

`cd build-desktop-edm-g-imx8mp/tmp/deploy/images/edm-g-imx8mp
`

You can flash image by following command:

**To SD card:**

`sudo dd if=imx-image-desktop-edm-g-imx8mp.wic.bz2 of=/dev/sdX bs=1M`

or

sudo bmaptool copy imx-image-desktop-edm-g-imx8mp.wic.bz2 /dev/sdX

**To eMMC:**

Install uuu tool in ubuntu host PC:
`# bash <(wget -qO- https://raw.githubusercontent.com/TechNexion-customization/uuu_install_script/master/uuu_install_script.sh)
`

Install required packages for running mfgtool (uuu). The following command will install them onto an Ubuntu host machine.

`sudo apt-get install libusb-1.0.0-dev libzip-dev libbz2-dev`


Switch the board to serial download mode (keep pressing the button below while power it up)
![圖片](https://user-images.githubusercontent.com/6065214/159419351-ac99f0a0-da48-45d4-be62-5e036ef612bb.png)


Insert type-C cable to board and ubuntu host PC: 
(It's better to use USB 2.0 instead USB 3.0 port. We found `uuu` can't work well with USB 3.0 on some PC.)
`sudo uuu_flash -b edm-g-imx8mp -i imx-image-desktop-edm-g-imx8mp.wic.bz2`

![圖片](https://user-images.githubusercontent.com/6065214/159420508-d76184c8-129c-484f-81bb-7e224fe4d365.png)

**Reference:**
https://github.com/TechNexion/u-boot-tn-imx/wiki/EDM%E2%80%90G%E2%80%90IMX8MP
https://developer.technexion.com/docs/using-uuu-to-flash-emmc


BR,

Richard

**Comment by LeoChang88** [comment]
@richard-hu 

I used "sudo dd if=imx-image-desktop-edm-g-imx8mp.wic.bz2 of=/dev/sdX bs=1M" to flash my sd card and change sw1 config:
![image](https://user-images.githubusercontent.com/80381705/159429616-7968c58a-24db-406f-9ac6-0d646f8fbd55.png)

but the carrier board does not boot.

**Comment by richard-hu** [comment]
@LeoChang88 

`/dev/sdX` means the block device of SD card shown on your computer.
You can use `lsblk` command to check what is the block device for your SD card.

**Comment by LeoChang88** [comment]
@richard-hu 
Yes, my SD card path is /dev/sdb, I already modified it.

**Comment by richard-hu** [comment]
@LeoChang88 

Is there any output from debug console?

**Comment by LeoChang88** [comment]
@richard-hu 
No, but after i tried to use bmaptool to flash my SD card, it was boot successfully.

**Comment by richard-hu** [comment]
Need to decompress bz2 file first.
bzip2 -d imx-image-desktop-edm-g-imx8mp.wic.bz2
sudo dd if=imx-image-desktop-edm-g-imx8mp.wic of=/dev/sdX bs=1M
