### ISSUE TITLE
fail to compile image of pico-iMX8mq platform 

### ISSUE THREAD

**Issue by JomaskTsai** [TechNexion/tn-imx-yocto-manifest#29]
Hi,
I had followed the instructions of branch hardknott_5.10.y-stable.
but i compiled it fail. 
the error message I met is as below 
-----

| cc1plus: error: include location "/usr/include/CL" is unsafe for cross-compilation [-Werror=poison-system-directories]
| cc1plus: all warnings being treated as errors
| ninja: build stopped: subcommand failed.
| WARNING: exit code 1 from a shell command.
| ERROR: Execution of '/XXX/edm_yocto/build-xwayland-pico-imx8mq/tmp/work/cortexa53-crypto-poky-linux/tim-vx/1.1.34-r0/temp/run.do_compile.130058' failed with exit code 1

------
is there anyone knows how to solve it?

Thanks a lot

**Comment by richard-hu** [comment]
@JomaskTsai :

We just test the build for PICO-IMX8MQ.
The build of `tim-vx` completes without errors.
![圖片](https://user-images.githubusercontent.com/6065214/159645554-a25fa8f7-f7d4-40df-8101-99ca94b80a5a.png)


```
repo init -u https://github.com/TechNexion/tn-imx-yocto-manifest.git -b hardknott_5.10.y-stable -m imx-5.10.72-2.2.0-2022Q1.xml

repo sync -j8

WIFI_FIRMWARE=y DISTRO=fsl-imx-xwayland MACHINE=pico-imx8mq source tn-setup-release.sh -b build-xwayland-pico-imx8mq

bitbake tim-vx
```


Could you share more details about the commands  and host environment(what is the ubuntu version on host PC)? 

BR,

Richard

**Comment by JomaskTsai** [comment]
Hi Richard:
Thanks for your response.
I found the root cause.
I had installed the OpenCL driver Ubuntu version before.
Now I can finish the compilation after uninstalling opencl.
