### ISSUE TITLE
xore wizard ov7251 camera

### ISSUE THREAD

**Issue by arrow53** [TechNexion/tn-imx-yocto-manifest#3]
I have an xore wizard kit with the ov7251 camera. I see a driver for it in the community kernel but nothing in https://github.com/TechNexion/linux-tn-imx. I can pull in that driver but thought I'd ask if you have a patch against linux-tn-imx I could use.

**Comment by johnweber** [comment]
Hi, We do have a patch for this. Can I get contact information from you? You can send me email at john.weber@technexion.com
