### ISSUE TITLE
edm-g-IMX8MP pcie not working

### ISSUE THREAD

**Issue by LeoChang88** [TechNexion/tn-imx-yocto-manifest#31]
Hello,

I'm testing about the PCIE on M.2 Key B, but we cannot detect any device by lspci,
please help to check this issue, thanks.
[pcie_dmesg.log](https://github.com/TechNexion/tn-imx-yocto-manifest/files/8479641/pcie_dmesg.log)

**Comment by wigcheng** [comment]
What kind of PCIE device, WiFi? NVME SSD or something else?

**Comment by LeoChang88** [comment]
5G module.

**Comment by wigcheng** [comment]
Any specific product ID? 5G function via PCIE is a very modular function, so the driver only support on kernel 5.15 or above (MHI driver).

But you can trying to backport to current kernel, or connect to our sales window, we'll support you after signature contract.

An easy way is change to USB mode, should be works as well.
