### ISSUE TITLE
TEP0500-IMX

### ISSUE THREAD

**Issue by cherifseye** [TechNexion/tn-imx-yocto-manifest#33]
Hello, i was wondering if after following this tutorial i can install python3 on my Yocto? 
Also what's the name of machine of the TEP-0500-IMX6
Thanks

**Comment by richard-hu** [comment]
@cherifseye :

Thanks for the feedback~

Is the product name `TEP-0500-IMX6UL` or `TEP-0500-IMX7`?
https://www.technexion.com/products/panel-computing/modular-hmi-series/tep-0500-imx6ul/
https://www.technexion.com/products/panel-computing/modular-hmi-series/tep-0500-imx7/

If the product name is `TEP-0500-IMX6UL`, the machine name is `TEP1-IMX6UL`.

There is prebuilt image on TechNexion file server:
https://download.technexion.com/demo_software/TEP/IMX6/tep0500-imx6ul/Installer/

The last yocto release - Yocto 2.1 is based on the source code below:
https://github.com/TechNexion/meta-edm-bsp-release/tree/krogoth_4.1.y_GA

The BSP is outdated, i am not sure if the build still works.

BR,

Richard

**Comment by cherifseye** [comment]
Thankks a lot for your hel^p, btw the name of the product was the TEP-0500-IMX6UL,

Cherif
