### ISSUE TITLE
ncurses_6.2.bb:do_install failed with exit code '1'

### ISSUE THREAD

**Issue by navinagaraj** [TechNexion/tn-imx-yocto-manifest#35]
Hi, I tried to build for wandboard-imx6 but facing issues.

Step-1 = DISTRO=fsl-imx-wayland MACHINE=wandboard-imx6 source tn-setup-release.sh -b build-WANDBOARD
Step-2 = bitbake imx-image-full

![ncurses-error](https://user-images.githubusercontent.com/42691369/185043179-4ef3d880-0840-4f19-ad4c-f006d94b1c73.png)

**Comment by richard-hu** [comment]
Hi, @navinagaraj :

Thanks for your feedback.

Could you share more information about what version of Yocto you use ?


BR,

Richard

**Comment by navinagaraj** [comment]
Hi @richard-hu,

I am new to yocto, I just followed the steps from https://github.com/TechNexion/tn-imx-yocto-manifest/tree/hardknott_5.10.y-stable
Can you share the build steps wandbord 5.10.72-2.2.0

**Comment by navinagaraj** [comment]
Hi @richard-hu can you help me to clear this issue?

**Comment by richard-hu** [comment]
@navinagaraj :

Thanks for your feedback.
Sorry for the late reply.
We just publish the latest Yocto 3.3 Hardknott release.
Wandboard-imx6 is supported in this release. (The build is tested on our CI server.)
https://download.technexion.com/demo_software/WANDBOARD/wandboard-imx6/DiskImage/wandboard-imx6_yocto-3.3-qt5_qca9377_20220822.zip

Could you update the yocto source to fetch `5.10.72-2.2.0-2022Q2`?
https://github.com/TechNexion/tn-imx-yocto-manifest

```
$: repo init -u https://github.com/TechNexion/tn-imx-yocto-manifest.git -b hardknott_5.10.y-stable -m imx-5.10.72-2.2.0-2022Q2.xml
$: repo sync -j8
```

BR,

Richard

**Comment by navinagaraj** [comment]
Hi,
 @richard-hu Thanks for your reply. yes, I fetched from 5.10.72-2.2.0-2022Q2, I shared the steps I followed.
[yocto-steps.txt](https://github.com/TechNexion/tn-imx-yocto-manifest/files/9413127/yocto-steps.txt)

**Comment by navinagaraj** [comment]
HI @richard-hu the following steps ok?

**Comment by richard-hu** [comment]
Hi, @navinagaraj : 

Yes, It looks good.
The build passes in my local environment.(We apply the build instructions you provide.) 

![圖片](https://user-images.githubusercontent.com/6065214/186559540-4f363b6e-2630-4ef4-bdeb-32b7cdf090ed.png)

![圖片](https://user-images.githubusercontent.com/6065214/186559202-50b6456e-a21d-4f22-b4b5-48629c18cec3.png)

BR,

Richard

**Comment by navinagaraj** [comment]
The build success in ubuntu-20.04-LTS, But it did not succeed in 18.04-LTS, is that any host requirement issue in 18.04?
