### ISSUE TITLE
pico-imx8mm Yocto hardknott build fails (Docker)

### ISSUE THREAD

**Issue by paoloturim** [TechNexion/tn-imx-yocto-manifest#42]
https://developer.technexion.com/docs/building-an-image-in-docker-container

Hi,

I am facing problems using the link above and the commands below (Note: my internet is of excellent quality):

sudo docker run -it -u jenkins -v ${directory_in_host_machine}:${directory_in_docker} tn-develop-ubuntu bash

repo init -u https://github.com/TechNexion/tn-imx-yocto-manifest.git -b hardknott_5.10.y-stable -m imx-5.10.72-2.2.0-2022Q2.xml
repo sync -j8
WIFI_FIRMWARE=y DISTRO=fsl-imx-xwayland MACHINE=pico-imx8mm source tn-setup-release.sh -b build-xwayland-pico-imx8mm

```
ERROR: armnn-tensorflow-protobuf-2.3.1-r0 do_fetch: Fetcher failure: Fetch command export PSEUDO_DISABLED=1; export PATH="/edm_yocto/sources/poky/scripts:/edm_yocto/build-xwayland-pico-imx8mm/tmp/work/cortexa53-crypto-poky-linux/armnn-tensorflow-protobuf/2.3.1-r0/recipe-sysroot-native/usr/bin/aarch64-poky-linux:/edm_yocto/build-xwayland-pico-imx8mm/tmp/work/cortexa53-crypto-poky-linux/armnn-tensorflow-protobuf/2.3.1-r0/recipe-sysroot/usr/bin/crossscripts:/edm_yocto/build-xwayland-pico-imx8mm/tmp/work/cortexa53-crypto-poky-linux/armnn-tensorflow-protobuf/2.3.1-r0/recipe-sysroot-native/usr/sbin:/edm_yocto/build-xwayland-pico-imx8mm/tmp/work/cortexa53-crypto-poky-linux/armnn-tensorflow-protobuf/2.3.1-r0/recipe-sysroot-native/usr/bin:/edm_yocto/build-xwayland-pico-imx8mm/tmp/work/cortexa53-crypto-poky-linux/armnn-tensorflow-protobuf/2.3.1-r0/recipe-sysroot-native/sbin:/edm_yocto/build-xwayland-pico-imx8mm/tmp/work/cortexa53-crypto-poky-linux/armnn-tensorflow-protobuf/2.3.1-r0/recipe-sysroot-native/bin:/edm_yocto/sources/poky/bitbake/bin:/edm_yocto/build-xwayland-pico-imx8mm/tmp/hosttools"; export HOME="/home/jenkins"; LANG=C git -c core.fsyncobjectfiles=0 clone --bare --mirror https://github.com/tensorflow/tensorflow.git /edm_yocto/downloads//git2/github.com.tensorflow.tensorflow.git --progress failed with exit code 128, no output
ERROR: armnn-tensorflow-protobuf-2.3.1-r0 do_fetch: Fetcher failure for URL: 'git://github.com/tensorflow/tensorflow.git;branch=r2.3;name=tensorflow'. Unable to fetch URL from any source.
ERROR: Logfile of failure stored in: /edm_yocto/build-xwayland-pico-imx8mm/tmp/work/cortexa53-crypto-poky-linux/armnn-tensorflow-protobuf/2.3.1-r0/temp/log.do_fetch.1064356
ERROR: Task (/edm_yocto/sources/meta-imx/meta-ml/recipes-libraries/armnn/armnn-tensorflow-protobuf_2.3.1.bb:do_fetch) failed with exit code '1'
```

**Comment by ray-chang** [comment]
@paoloturim 

Thanks for the feedback.

Yocto collects a lot of opensource and 3rd party packages.
All the package are maintained by 3rd-party organizations and companies.
Also in Yocto document, it suggests to set up local mirror file server to get rid of this kind of problem.

If you're building a completely new environment, it's not recommended to use hardknott. Because hardknott has been EOL for a long time.
![image](https://github.com/TechNexion/tn-imx-yocto-manifest/assets/7445644/f872a4df-5209-46bd-8cbd-56d1f68ba152)

We keep the "download" and "sstate" cache directories on our CI server, so we can build them as well.

BR,
Ray

**Comment by paoloturim** [comment]
```
MACHINE=pico-imx8mm DISTRO=fsl-imx-xwayland source tn-setup-release.sh -b build-xwayland
bitbake imx-image-core

```
Finally I managed to generate my Kirkstone image for pico-imx8mm Using native Ubuntu 22.04 (non-docker)
But, not without having to give these two commands below:
bitbake rust-llvm-native -c cleansstate
bitbake rust-llvm-native
