### ISSUE TITLE
Support for TEP-0700-IMX7 with Yocto 4.2 Mickledore 6.1

### ISSUE THREAD

**Issue by JeanPhilippeLebel** [TechNexion/tn-imx-yocto-manifest#46]
Hello,

Based on the read-me, TEP-0700-IMX7 is not supported by the Yocto 4.2 Mickledore 6.1 BSP. 

Is this correct?

Thanks

**Comment by ray-chang** [comment]
@JeanPhilippeLebel 

Thanks for the feedback.
We will be updating this month to support TEP-0700-IMX7. Thank you for your patience.

BR,
Ray

**Comment by richard-hu** [comment]
@JeanPhilippeLebel 

Thanks for your patience!

The download link of preview image is as below:
https://download.technexion.com/demo_software/TEP/IMX7/tep0700-imx7d/DiskImage/

BR,

Richard

**Comment by JeanPhilippeLebel** [comment]
@richard-hu Thanks for the follow-up. I will give it a try.
