### ISSUE TITLE
git:// protocol issue

### ISSUE THREAD

**Issue by Livius90** [TechNexion/tn-imx-yocto-manifest#5]
Hi!
In most of company, internal-network proxy server is not configured to use git://.
Can you use https:// for all git urls in all Technexion manifest and projects in github?
It could be helpfully to me and many other employee in any other company.

Example:
Use https://github.com/ instead of git://github.com/
Do not use git:// for poky and meta-freescale use their https:// urls instead.
https://git.yoctoproject.org/git/meta-freescale
https://git.yoctoproject.org/git/poky

You can check these https links in the website of the repos.
[http://git.yoctoproject.org/cgit/cgit.cgi/meta-freescale/](http://git.yoctoproject.org/cgit/cgit.cgi/meta-freescale/)
[http://git.yoctoproject.org/cgit/cgit.cgi/poky/](http://git.yoctoproject.org/cgit/cgit.cgi/poky/)

**Comment by po-cheng-technexion** [comment]
Updated to http for 4.14.98-next and 5.4.47-next branch
