### ISSUE TITLE
build the sdk at imx-4.14.98-2.0.1_patch.xml

### ISSUE THREAD

**Issue by kikiyami** [TechNexion/tn-imx-yocto-manifest#8]
Hi,
I try to build the sdk of version 4.14.98-2.0.1_patch and got error messages as below:

note : next branch
Thanks
----------------------------------------------------------------------------------------------------------
Build Configuration:
BB_VERSION           = "1.38.0"
BUILD_SYS            = "x86_64-linux"
NATIVELSBSTRING      = "ubuntu-16.04"
TARGET_SYS           = "arm-poky-linux-gnueabi"
MACHINE              = "edm-imx6"
DISTRO               = "fsl-imx-x11"
DISTRO_VERSION       = "4.14-sumo"
TUNE_FEATURES        = "arm armv7a vfp neon callconvention-hard cortexa9"
TARGET_FPU           = "hard"
meta                 
meta-poky            = "HEAD:c9bd4984f8f471ca2c43052714f4413ba99cf171"
meta-oe              
meta-multimedia      = "HEAD:8760facba1bceb299b3613b8955621ddaa3d4c3f"
meta-freescale       = "HEAD:27ca94f8a4336790ba117b4298566f6820e7e74c"
meta-freescale-3rdparty = "HEAD:82037216280a39957fb4272581637abec734ad50"
meta-freescale-distro = "HEAD:f7e2216e93aff14ac32728a13637a48df436b7f4"
meta-tn-imx-bsp      = "HEAD:1eb8da9c2b2b498306b50ec00c1d24eba68463aa"
meta-bsp             
meta-sdk             = "HEAD:238a429e4eedd2f4b26876c2e2a6a9b3ec4e434c"
meta-browser         = "HEAD:75640e14e325479c076b6272b646be7a239c18aa"
meta-gnome           
meta-networking      
meta-python          
meta-filesystems     = "HEAD:8760facba1bceb299b3613b8955621ddaa3d4c3f"
meta-qt5             = "HEAD:d4e7f73d04e8448d326b6f89908701e304e37d65"
meta-multimedia      = "HEAD:8760facba1bceb299b3613b8955621ddaa3d4c3f"
meta-nxp-nfc         = "HEAD:5d05c57fc8faf3f1bc95c1702e1a6aa78d83412f"

ERROR: Task do_polulate_sdk does not exist for target fsl-image-qt5-validation-imx (/video/technexion/edm_yocto/sources/meta-fsl-bsp-release/imx/meta-sdk/dynamic-layers/qt5-layer/recipes-fsl/images/fsl-image-qt5-validation-imx.bb:do_polulate_sdk). Close matches:
  do_populate_sdk
  do_populate_sdk_ext
  do_populate_lic
ERROR: Command execution failed: 1

**Comment by po-cheng-technexion** [comment]
Check your spelling, the task should be do_populate_sdk, not do_polulate_sdk
